### ISSUE TITLE
lack some npm dependencies which lead to failed to render layout

### ISSUE THREAD

**Issue by lordfriend** [hexojs/hexo-theme-unit-test#1]
When starting a new hexo blog using `hexo init` it will be created a package.json contains the following dependencies:

``` json
 "dependencies": {
    "hexo-renderer-ejs": "*",
    "hexo-renderer-stylus": "*",
    "hexo-renderer-marked": "*"
  }
```

but the package.json file of this unit test project contains no dependencies. When I run `hexo server` even using the landscape theme, I only get the plain ejs file.

Maybe this is ignored intentionally. for example, someone may create a theme using jade instead of ejs. but it is recommended to declare this in the readme file to avoid misconception.

**Comment by Xuanwo** [comment]
I will fix it later
