### ISSUE TITLE
本地开发时，有几张图片显示不出来

### ISSUE THREAD

**Issue by geekplux** [hexojs/hexo-theme-unit-test#2]
![29ffe4e3-bd10-4f73-9927-af82ff47f28d](https://cloud.githubusercontent.com/assets/3816105/9725432/d97760cc-5617-11e5-9bdc-f3d6805bb1b0.png)
![478e508e-f91c-4bc5-b6af-a1b7c2879790](https://cloud.githubusercontent.com/assets/3816105/9725431/d97732d2-5617-11e5-89ae-4319ca9efa54.png)

应该是没有把source 文件夹下的图片移到指定文件夹。。

**Comment by Xuanwo** [comment]
图片的调用链接不对

请区分`/path/xxx.jpg`和`path/xx.jpg`

**Comment by geekplux** [comment]
@Xuanwo 直接clone 下来，hexo init & npm install，再 hexo s --debug 运行的，没改过什么地方

**Comment by Xuanwo** [comment]
你看一下生成之后的gallery-post文件夹在哪里

**Comment by geekplux** [comment]
看过了，gallery-post文件夹的位置是对的，只是里面没图片，所以说明是图片没移过去

**Comment by Xuanwo** [comment]
`gallery-post文件夹的位置是对的`，所以是在哪里？

**Comment by geekplux** [comment]
![1e2fdd79-64b6-4c27-aac6-8e4ac8cd15f0](https://cloud.githubusercontent.com/assets/3816105/9725738/735394e2-561b-11e5-8ebf-165c94621962.png)

**Comment by Xuanwo** [comment]
这个文件夹肯定是会有的- -，因为有个md文件名字就叫这个。
有些不太理解，之前用的时候是没有问题的，新版本对`_post`下jpg文件的处理方式有变动么？我留意一下吧，有空的时候看一下源码。

现在的话，先把图片文件夹移动到`/source`目录下，用`/lallery/xx.jpg`的形式调用吧

对了，麻烦顺便看一下你的public目录下哪个路径有图片~

**Comment by geekplux** [comment]
是的，我估计是新版本对_post文件夹里图片的处理方式变了。。。因为2.x版本的时候没问题

**Comment by Xuanwo** [comment]
= =，这个库也有点年头了。。我都快忘记这个库了。。
要不这样，你把那个文件挪出来，然后修复一下图片的链接，交个PR，我来合并~

**Comment by Xuanwo** [comment]
恩，晚点我来修复一下吧~
正好还有一些依赖库之类的问题还需要修复
